import {PATHS} from "../../utils/constants";

const {OPERATORS, CERTIFICATES, NOTIFICATIONS, CLIENTS, ROLES, PREFERENCES, MYCOMPANY} = PATHS

export const USER_ROLES = {
    TEST: {
        key: 'TEST',
        access: [
            OPERATORS.INDEX, OPERATORS.CREATE, OPERATORS.EDIT, OPERATORS.SHOW,
            CERTIFICATES.INDEX, CERTIFICATES.CREATE, CERTIFICATES.EDIT, CERTIFICATES.SHOW,
            CLIENTS.INDEX, CLIENTS.CREATE, CLIENTS.EDIT, CLIENTS.SHOW,
            ROLES.INDEX, ROLES.CREATE, ROLES.EDIT, ROLES.SHOW,
            NOTIFICATIONS.INDEX,
            MYCOMPANY.INDEX, MYCOMPANY.EDIT,
            PREFERENCES
        ]
    },
    PLANER: {
        key: 'PLANER',
        access: [
            OPERATORS.INDEX, OPERATORS.CREATE, OPERATORS.EDIT, OPERATORS.SHOW,
            NOTIFICATIONS.INDEX,
            CERTIFICATES.INDEX, CERTIFICATES.SHOW,
            CLIENTS.INDEX, CLIENTS.SHOW,
            ROLES.INDEX, ROLES.SHOW,
            PREFERENCES
        ]
    },
    CLIENT: {
        key: 'CLIENT',
        access: [
            ROLES.INDEX, ROLES.CREATE, ROLES.EDIT, ROLES.SHOW,
            NOTIFICATIONS.INDEX,
            MYCOMPANY.INDEX, MYCOMPANY.EDIT,
            PREFERENCES
        ]
    },
    ISSUER: {
        key: 'ISSUER',
        access: [
            CERTIFICATES.INDEX, CERTIFICATES.CREATE, CERTIFICATES.EDIT, CERTIFICATES.SHOW,
            NOTIFICATIONS.INDEX,
            MYCOMPANY.INDEX, MYCOMPANY.EDIT,
            PREFERENCES
        ]
    }
}
